In [1]:
import mdacore
import numpy as np

ortho_box = np.arange(6, dtype=np.float32)

In [2]:
mdacore.TimestepContainer

mdacore.TimestepContainer

In [3]:
%%time 
tstep = mdacore.TimestepContainer(10,dtype=np.float64)
tstep

CPU times: user 35 µs, sys: 6 µs, total: 41 µs
Wall time: 47.7 µs


In [4]:
pos_in = np.arange(30, dtype=np.float32).reshape(10,3)
pos_in

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [5]:
tstep.positions = pos_in
tstep.has_positions



True

In [6]:
a = tstep.positions
type(a)


numpy.ndarray

In [7]:
tstep.positions += 10

In [8]:
tstep.positions

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.],
       [22., 23., 24.],
       [25., 26., 27.],
       [28., 29., 30.],
       [31., 32., 33.],
       [34., 35., 36.],
       [37., 38., 39.]])

In [9]:
tstep.dimensions = np.arange(6, dtype=np.float32)
b = tstep.dimensions

In [10]:
a = tstep.positions
a

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.],
       [22., 23., 24.],
       [25., 26., 27.],
       [28., 29., 30.],
       [31., 32., 33.],
       [34., 35., 36.],
       [37., 38., 39.]])

In [11]:
tstep.has_positions

True

In [12]:
del tstep

In [13]:
b

array([0., 1., 2., 3., 4., 5.])

In [14]:
a

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.],
       [22., 23., 24.],
       [25., 26., 27.],
       [28., 29., 30.],
       [31., 32., 33.],
       [34., 35., 36.],
       [37., 38., 39.]])

In [15]:
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD, GRO, XTC

u= mda.Universe(GRO, XTC)
print(mda.__version__)

/home/hmacdope/anaconda3/envs/mdacore_devel/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2.2.0-dev0


In [16]:
for ts in u.trajectory:
    print(ts)

< Timestep 0 with unit cell dimensions [80.017006 80.017006 80.017006 60.       60.       90.      ] >
< Timestep 1 with unit cell dimensions [80.13008 80.13008 80.13008 60.      60.      90.     ] >
< Timestep 2 with unit cell dimensions [79.98359 79.98359 79.98358 60.      60.      90.     ] >
< Timestep 3 with unit cell dimensions [80.00516 80.00516 80.00516 60.      60.      90.     ] >
< Timestep 4 with unit cell dimensions [80.13544 80.13544 80.13544 60.      60.      90.     ] >
< Timestep 5 with unit cell dimensions [80.07649  80.07649  80.076485 59.999996 59.999996 90.      ] >
< Timestep 6 with unit cell dimensions [79.93229 79.93229 79.93228 60.      60.      90.     ] >
< Timestep 7 with unit cell dimensions [79.95813 79.95813 79.95813 60.      60.      90.     ] >
< Timestep 8 with unit cell dimensions [80.11252 80.11252 80.11252 60.      60.      90.     ] >
< Timestep 9 with unit cell dimensions [80.08523 80.08523 80.08523 60.      60.      90.     ] >


In [17]:
b = ts.dimensions
b

array([80.017006, 80.017006, 80.017006, 60.      , 60.      , 90.      ],
      dtype=float32)

In [18]:
ts.positions.shape

(47681, 3)

In [19]:
b += 4

In [20]:
b

array([84.017006, 84.017006, 84.017006, 64.      , 64.      , 94.      ],
      dtype=float32)

In [21]:
ts.dimensions

array([84.017006, 84.017006, 84.017006, 64.      , 64.      , 94.      ],
      dtype=float32)

In [22]:
from MDAnalysis.coordinates.base import Timestep

In [23]:
%%time
t = Timestep(10)
t

CPU times: user 68 µs, sys: 23 µs, total: 91 µs
Wall time: 98.7 µs


< Timestep -1 with unit cell dimensions None >

In [24]:
%%time 
tstep = mdacore.TimestepContainer(10,dtype=np.float64)
tstep

CPU times: user 34 µs, sys: 11 µs, total: 45 µs
Wall time: 52.2 µs


In [25]:
tstep.positions

ValueError: This Timestep has no position information

In [26]:
tstep.dimensions

ValueError: This Timestep has no dimension information