In [1]:
import mdacore
import numpy as np

ortho_box = np.arange(6)

In [2]:
mdacore.Timestep_F_F

mdacore.Timestep_F_F

In [3]:
tstep = mdacore.Timestep_F_F(10, ortho_box)

In [5]:
b = tstep.dimensions


In [6]:
b

array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [7]:
b += 4

In [8]:
b

array([4., 5., 6., 7., 8., 9.], dtype=float32)

In [9]:
tstep.dimensions

array([4., 5., 6., 7., 8., 9.], dtype=float32)

In [10]:
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD, GRO, XTC

u= mda.Universe(GRO, XTC)
print(mda.__version__)

2.2.0-dev0


In [11]:
for ts in u.trajectory:
    print(ts)

< Timestep 0 with unit cell dimensions [80.017006 80.017006 80.017006 60.       60.       90.      ] >
< Timestep 1 with unit cell dimensions [80.13008 80.13008 80.13008 60.      60.      90.     ] >
< Timestep 2 with unit cell dimensions [79.98359 79.98359 79.98358 60.      60.      90.     ] >
< Timestep 3 with unit cell dimensions [80.00516 80.00516 80.00516 60.      60.      90.     ] >
< Timestep 4 with unit cell dimensions [80.13544 80.13544 80.13544 60.      60.      90.     ] >
< Timestep 5 with unit cell dimensions [80.07649  80.07649  80.076485 59.999996 59.999996 90.      ] >
< Timestep 6 with unit cell dimensions [79.93229 79.93229 79.93228 60.      60.      90.     ] >
< Timestep 7 with unit cell dimensions [79.95813 79.95813 79.95813 60.      60.      90.     ] >
< Timestep 8 with unit cell dimensions [80.11252 80.11252 80.11252 60.      60.      90.     ] >
< Timestep 9 with unit cell dimensions [80.08523 80.08523 80.08523 60.      60.      90.     ] >


In [12]:
b = ts.dimensions

In [13]:
b

array([80.017006, 80.017006, 80.017006, 60.      , 60.      , 90.      ],
      dtype=float32)

In [14]:
ts.positions.shape

(47681, 3)

In [15]:
b += 4

In [16]:
b

array([84.017006, 84.017006, 84.017006, 64.      , 64.      , 94.      ],
      dtype=float32)

In [17]:
ts.dimensions

array([84.017006, 84.017006, 84.017006, 64.      , 64.      , 94.      ],
      dtype=float32)

In [18]:
tstep.positions = np.arange(30, dtype=np.float32)

In [ ]:
tstep.positions += 10

In [22]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)