In [1]:
import mdacore
import numpy as np

ortho_box = np.arange(6, dtype=np.float32)

In [2]:
mdacore.TimestepContainer

mdacore.TimestepContainer

In [3]:
tstep = mdacore.TimestepContainer(10, np.float32, np.float32)
tstep

In [4]:
pos_in = np.arange(30, dtype=np.float32).reshape(10,3)
pos_in

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [6]:
tstep.positions = pos_in
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [7]:
tstep.positions += 10

In [8]:
tstep.positions

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.],
       [19., 20., 21.],
       [22., 23., 24.],
       [25., 26., 27.],
       [28., 29., 30.],
       [31., 32., 33.],
       [34., 35., 36.],
       [37., 38., 39.]], dtype=float32)

In [13]:
 tstep.dimensions = np.arange(6, dtype=np.float32).reshape(3,2)


ValueError: box cannot be set with multidimensional array

In [ ]:
b

In [ ]:
b += 4

In [ ]:
b

In [ ]:
tstep.dimensions

In [ ]:
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD, GRO, XTC

u= mda.Universe(GRO, XTC)
print(mda.__version__)

In [ ]:
for ts in u.trajectory:
    print(ts)

In [ ]:
b = ts.dimensions

In [ ]:
b

In [ ]:
ts.positions.shape

In [ ]:
b += 4

In [ ]:
b

In [ ]:
ts.dimensions