In [1]:
import mdacore
import numpy as np
import gc

ortho_box = np.arange(6, dtype=np.float32)

In [2]:
mdacore.TimestepContainer

mdacore.TimestepContainer

In [3]:
tstep = mdacore.TimestepContainer(10,dtype=np.float32)
tstep

In [4]:
pos_in = np.arange(30, dtype=np.float32).reshape(10,3)
pos_in

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [5]:
vel_in = pos_in*2
vel_in

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.],
       [30., 32., 34.],
       [36., 38., 40.],
       [42., 44., 46.],
       [48., 50., 52.],
       [54., 56., 58.]], dtype=float32)

In [6]:
frc_in = pos_in*3
frc_in

array([[ 0.,  3.,  6.],
       [ 9., 12., 15.],
       [18., 21., 24.],
       [27., 30., 33.],
       [36., 39., 42.],
       [45., 48., 51.],
       [54., 57., 60.],
       [63., 66., 69.],
       [72., 75., 78.],
       [81., 84., 87.]], dtype=float32)

In [7]:
%%timeit tstep.positions = pos_in
tstep.positions

28.9 ns ± 0.37 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [8]:
tstep.velocities = vel_in
tstep.velocities

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.],
       [30., 32., 34.],
       [36., 38., 40.],
       [42., 44., 46.],
       [48., 50., 52.],
       [54., 56., 58.]], dtype=float32)

In [9]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [10]:
tstep.forces = frc_in
tstep.forces

array([[ 0.,  3.,  6.],
       [ 9., 12., 15.],
       [18., 21., 24.],
       [27., 30., 33.],
       [36., 39., 42.],
       [45., 48., 51.],
       [54., 57., 60.],
       [63., 66., 69.],
       [72., 75., 78.],
       [81., 84., 87.]], dtype=float32)

In [11]:
tstep.velocities

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.],
       [30., 32., 34.],
       [36., 38., 40.],
       [42., 44., 46.],
       [48., 50., 52.],
       [54., 56., 58.]], dtype=float32)

In [12]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [13]:
tstep.positions = pos_in

In [14]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [15]:
tstep.dimensions = ortho_box
tstep.dimensions




array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [16]:
tstep.dimensions = ortho_box
tstep.dimensions


array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [17]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [18]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [19]:
d = tstep.positions
d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [20]:
inp = np.arange(100000, dtype=np.float32)
out = np.zeros(100000, dtype=np.float32)

In [21]:
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD, GRO, XTC

u= mda.Universe(GRO, XTC)
print(mda.__version__)

/home/hmacdope/anaconda3/envs/mdacore_devel/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2.2.0-dev0


In [22]:
for ts in u.trajectory:
    print(ts)

< Timestep 0 with unit cell dimensions [80.017006 80.017006 80.017006 60.       60.       90.      ] >
< Timestep 1 with unit cell dimensions [80.13008 80.13008 80.13008 60.      60.      90.     ] >
< Timestep 2 with unit cell dimensions [79.98359 79.98359 79.98358 60.      60.      90.     ] >
< Timestep 3 with unit cell dimensions [80.00516 80.00516 80.00516 60.      60.      90.     ] >
< Timestep 4 with unit cell dimensions [80.13544 80.13544 80.13544 60.      60.      90.     ] >
< Timestep 5 with unit cell dimensions [80.07649  80.07649  80.076485 59.999996 59.999996 90.      ] >
< Timestep 6 with unit cell dimensions [79.93229 79.93229 79.93228 60.      60.      90.     ] >
< Timestep 7 with unit cell dimensions [79.95813 79.95813 79.95813 60.      60.      90.     ] >
< Timestep 8 with unit cell dimensions [80.11252 80.11252 80.11252 60.      60.      90.     ] >
< Timestep 9 with unit cell dimensions [80.08523 80.08523 80.08523 60.      60.      90.     ] >


In [23]:
dim = ts.dimensions
dim

array([80.017006, 80.017006, 80.017006, 60.      , 60.      , 90.      ],
      dtype=float32)

In [24]:
ts.positions.shape

(47681, 3)

In [25]:
dim += 4

In [26]:
dim 

array([84.017006, 84.017006, 84.017006, 64.      , 64.      , 94.      ],
      dtype=float32)

In [27]:
ts.dimensions

array([84.017006, 84.017006, 84.017006, 64.      , 64.      , 94.      ],
      dtype=float32)

In [33]:
from MDAnalysis.coordinates.base import Timestep
N= 60000
inp = np.arange(N*3, dtype=np.float32).reshape(N,3)

In [34]:
%%timeit
t = Timestep(N)


28 µs ± 892 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [35]:
%%timeit
cts = mdacore.TimestepContainer(N,dtype=np.float32)


200 ns ± 0.788 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [36]:
t = Timestep(N)
cts = mdacore.TimestepContainer(N,dtype=np.float32)


In [37]:
%%timeit
t.positions = inp

41.1 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [38]:
%%timeit
cts.positions = inp

44.8 ns ± 0.194 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [39]:
%%timeit
cts.forces = inp

42.3 ns ± 0.123 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [40]:
cts.forces

array([[0.00000e+00, 1.00000e+00, 2.00000e+00],
       [3.00000e+00, 4.00000e+00, 5.00000e+00],
       [6.00000e+00, 7.00000e+00, 8.00000e+00],
       ...,
       [1.79991e+05, 1.79992e+05, 1.79993e+05],
       [1.79994e+05, 1.79995e+05, 1.79996e+05],
       [1.79997e+05, 1.79998e+05, 1.79999e+05]], dtype=float32)

In [41]:
%%timeit
t.positions

248 ns ± 1.78 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [42]:
%%timeit
cts.positions

29.3 ns ± 0.329 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [43]:
%%timeit
cts.dimensions = ortho_box

40.6 ns ± 0.104 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [44]:
%%timeit
cts.dimensions

29.2 ns ± 0.0218 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
