In [24]:
import mdacore
import numpy as np



In [25]:
N=100000
tstep = mdacore.TimestepContainer(N,dtype=np.float32)
tstep

In [26]:
pos_in = np.arange(3*N, dtype=np.float32).reshape(N,3)

pos_in_2 = np.arange(3*N, dtype=np.float32).reshape(N,3)*3

In [27]:
tstep.positions = pos_in

In [28]:
tstep.positions

array([[0.00000e+00, 1.00000e+00, 2.00000e+00],
       [3.00000e+00, 4.00000e+00, 5.00000e+00],
       [6.00000e+00, 7.00000e+00, 8.00000e+00],
       ...,
       [2.99991e+05, 2.99992e+05, 2.99993e+05],
       [2.99994e+05, 2.99995e+05, 2.99996e+05],
       [2.99997e+05, 2.99998e+05, 2.99999e+05]], dtype=float32)

In [45]:
pos_in = np.arange(3*N, dtype=np.float32).reshape(N,3)*3
pos_in


94581947952848

In [44]:
pos_in.__array_interface__["data"][0]

94581939582192

In [30]:
tstep.positions

array([[-1.5881942e-27,  3.0857993e-41, -2.0155643e-27],
       [ 3.0857993e-41,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  8.0000000e+00],
       ...,
       [ 2.9999100e+05,  2.9999200e+05,  2.9999300e+05],
       [ 2.9999400e+05,  2.9999500e+05,  2.9999600e+05],
       [ 2.9999700e+05,  2.9999800e+05,  2.9999900e+05]], dtype=float32)

In [31]:
tstep.positions = pos_in

In [32]:
tstep.positions

array([[0.00000e+00, 3.00000e+00, 6.00000e+00],
       [9.00000e+00, 1.20000e+01, 1.50000e+01],
       [1.80000e+01, 2.10000e+01, 2.40000e+01],
       ...,
       [8.99973e+05, 8.99976e+05, 8.99979e+05],
       [8.99982e+05, 8.99985e+05, 8.99988e+05],
       [8.99991e+05, 8.99994e+05, 8.99997e+05]], dtype=float32)

In [33]:
tstep.positions
tstep.positions
tstep.positions


array([[0.00000e+00, 3.00000e+00, 6.00000e+00],
       [9.00000e+00, 1.20000e+01, 1.50000e+01],
       [1.80000e+01, 2.10000e+01, 2.40000e+01],
       ...,
       [8.99973e+05, 8.99976e+05, 8.99979e+05],
       [8.99982e+05, 8.99985e+05, 8.99988e+05],
       [8.99991e+05, 8.99994e+05, 8.99997e+05]], dtype=float32)

In [34]:
pos_in = 1
pos_in

1

In [35]:
tstep.positions


array([[0.00000e+00, 3.00000e+00, 6.00000e+00],
       [9.00000e+00, 1.20000e+01, 1.50000e+01],
       [1.80000e+01, 2.10000e+01, 2.40000e+01],
       ...,
       [8.99973e+05, 8.99976e+05, 8.99979e+05],
       [8.99982e+05, 8.99985e+05, 8.99988e+05],
       [8.99991e+05, 8.99994e+05, 8.99997e+05]], dtype=float32)

In [36]:
pos_in = np.arange(3*N, dtype=np.float32).reshape(N,3)*3


In [37]:
tstep.positions


array([[0.00000e+00, 3.00000e+00, 6.00000e+00],
       [9.00000e+00, 1.20000e+01, 1.50000e+01],
       [1.80000e+01, 2.10000e+01, 2.40000e+01],
       ...,
       [8.99973e+05, 8.99976e+05, 8.99979e+05],
       [8.99982e+05, 8.99985e+05, 8.99988e+05],
       [8.99991e+05, 8.99994e+05, 8.99997e+05]], dtype=float32)

In [38]:
tstep.positions


array([[0.00000e+00, 3.00000e+00, 6.00000e+00],
       [9.00000e+00, 1.20000e+01, 1.50000e+01],
       [1.80000e+01, 2.10000e+01, 2.40000e+01],
       ...,
       [8.99973e+05, 8.99976e+05, 8.99979e+05],
       [8.99982e+05, 8.99985e+05, 8.99988e+05],
       [8.99991e+05, 8.99994e+05, 8.99997e+05]], dtype=float32)

In [39]:
tstep.positions=pos_in_2
tstep.positions

array([[0.00000e+00, 3.00000e+00, 6.00000e+00],
       [9.00000e+00, 1.20000e+01, 1.50000e+01],
       [1.80000e+01, 2.10000e+01, 2.40000e+01],
       ...,
       [8.99973e+05, 8.99976e+05, 8.99979e+05],
       [8.99982e+05, 8.99985e+05, 8.99988e+05],
       [8.99991e+05, 8.99994e+05, 8.99997e+05]], dtype=float32)

In [40]:
pos_in_2=np.zeros(3*N, dtype=np.float32)
pos_in_2

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [41]:
tstep.positions

array([[-1.5886549e-27,  3.0857993e-41,  4.9669598e-07],
       [ 4.5787427e-41, -1.5886549e-27,  3.0857993e-41],
       [-1.5886549e-27,  3.0857993e-41,  2.4000000e+01],
       ...,
       [ 8.9997300e+05,  8.9997600e+05,  8.9997900e+05],
       [ 8.9998200e+05,  8.9998500e+05,  8.9998800e+05],
       [ 8.9999100e+05,  8.9999400e+05,  8.9999700e+05]], dtype=float32)

In [42]:
tstep.positions = pos_in_2

In [43]:
tstep.positions

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)