In [1]:
import mdacore
import numpy as np
import gc
import sys
%load_ext memory_profiler


In [2]:
N=100000
tstep = mdacore.TimestepContainer(N,dtype=np.float32)
tstep

In [3]:
pos_in = np.arange(3*N, dtype=np.float32).reshape(N,3)

pos_in_2 = np.arange(3*N, dtype=np.float32).reshape(N,3)*3

In [4]:
tstep.positions = pos_in

In [5]:
sys.getrefcount(pos_in)

3

In [6]:
# del pos_in


In [7]:
sys.getrefcount(pos_in)

3

In [8]:
tstep.positions

array([[0.00000e+00, 1.00000e+00, 2.00000e+00],
       [3.00000e+00, 4.00000e+00, 5.00000e+00],
       [6.00000e+00, 7.00000e+00, 8.00000e+00],
       ...,
       [2.99991e+05, 2.99992e+05, 2.99993e+05],
       [2.99994e+05, 2.99995e+05, 2.99996e+05],
       [2.99997e+05, 2.99998e+05, 2.99999e+05]], dtype=float32)

In [9]:
pos_in = np.arange(3*N, dtype=np.float32).reshape(N,3)*3
pos_in

array([[0.00000e+00, 3.00000e+00, 6.00000e+00],
       [9.00000e+00, 1.20000e+01, 1.50000e+01],
       [1.80000e+01, 2.10000e+01, 2.40000e+01],
       ...,
       [8.99973e+05, 8.99976e+05, 8.99979e+05],
       [8.99982e+05, 8.99985e+05, 8.99988e+05],
       [8.99991e+05, 8.99994e+05, 8.99997e+05]], dtype=float32)

In [10]:
tstep.positions

array([[0.00000e+00, 1.00000e+00, 2.00000e+00],
       [3.00000e+00, 4.00000e+00, 5.00000e+00],
       [6.00000e+00, 7.00000e+00, 8.00000e+00],
       ...,
       [2.99991e+05, 2.99992e+05, 2.99993e+05],
       [2.99994e+05, 2.99995e+05, 2.99996e+05],
       [2.99997e+05, 2.99998e+05, 2.99999e+05]], dtype=float32)

In [11]:
gc.collect()

0