In [1]:
import mdacore
import numpy as np
import gc

ortho_box = np.arange(6, dtype=np.float32)

In [2]:
mdacore.TimestepContainer

mdacore.TimestepContainer

In [3]:
%%time 
tstep = mdacore.TimestepContainer(10,dtype=np.float64)
tstep

CPU times: user 28 µs, sys: 3 µs, total: 31 µs
Wall time: 38.9 µs


In [4]:
pos_in = np.arange(30, dtype=np.float32).reshape(10,3)
pos_in

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [5]:
vel_in = pos_in*2
vel_in

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.],
       [30., 32., 34.],
       [36., 38., 40.],
       [42., 44., 46.],
       [48., 50., 52.],
       [54., 56., 58.]], dtype=float32)

In [6]:
frc_in = pos_in*3
frc_in

array([[ 0.,  3.,  6.],
       [ 9., 12., 15.],
       [18., 21., 24.],
       [27., 30., 33.],
       [36., 39., 42.],
       [45., 48., 51.],
       [54., 57., 60.],
       [63., 66., 69.],
       [72., 75., 78.],
       [81., 84., 87.]], dtype=float32)

In [7]:
tstep.positions = pos_in
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]])

In [8]:
tstep.velocities = vel_in
tstep.velocities

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.],
       [30., 32., 34.],
       [36., 38., 40.],
       [42., 44., 46.],
       [48., 50., 52.],
       [54., 56., 58.]])

In [9]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]])

In [10]:
tstep.forces = frc_in
tstep.forces

array([[ 0.,  3.,  6.],
       [ 9., 12., 15.],
       [18., 21., 24.],
       [27., 30., 33.],
       [36., 39., 42.],
       [45., 48., 51.],
       [54., 57., 60.],
       [63., 66., 69.],
       [72., 75., 78.],
       [81., 84., 87.]])

In [11]:
tstep.velocities

array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.],
       [12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.],
       [30., 32., 34.],
       [36., 38., 40.],
       [42., 44., 46.],
       [48., 50., 52.],
       [54., 56., 58.]])

In [12]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]])

In [13]:
tstep.positions = pos_in

In [14]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]])

In [29]:
tstep.dimensions = ortho_box
tstep.dimensions




array([0., 1., 2., 3., 4., 5.])

In [30]:
tstep.dimensions = ortho_box
tstep.dimensions


array([0., 1., 2., 3., 4., 5.])

In [16]:
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD, GRO, XTC

u= mda.Universe(GRO, XTC)
print(mda.__version__)

/home/hmacdope/anaconda3/envs/mdacore_devel/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2.2.0-dev0


In [17]:
for ts in u.trajectory:
    print(ts)

< Timestep 0 with unit cell dimensions [80.017006 80.017006 80.017006 60.       60.       90.      ] >
< Timestep 1 with unit cell dimensions [80.13008 80.13008 80.13008 60.      60.      90.     ] >
< Timestep 2 with unit cell dimensions [79.98359 79.98359 79.98358 60.      60.      90.     ] >
< Timestep 3 with unit cell dimensions [80.00516 80.00516 80.00516 60.      60.      90.     ] >
< Timestep 4 with unit cell dimensions [80.13544 80.13544 80.13544 60.      60.      90.     ] >
< Timestep 5 with unit cell dimensions [80.07649  80.07649  80.076485 59.999996 59.999996 90.      ] >
< Timestep 6 with unit cell dimensions [79.93229 79.93229 79.93228 60.      60.      90.     ] >
< Timestep 7 with unit cell dimensions [79.95813 79.95813 79.95813 60.      60.      90.     ] >
< Timestep 8 with unit cell dimensions [80.11252 80.11252 80.11252 60.      60.      90.     ] >
< Timestep 9 with unit cell dimensions [80.08523 80.08523 80.08523 60.      60.      90.     ] >


In [18]:
b = ts.dimensions
b

array([80.017006, 80.017006, 80.017006, 60.      , 60.      , 90.      ],
      dtype=float32)

In [19]:
ts.positions.shape

(47681, 3)

In [20]:
b += 4

In [21]:
b

array([84.017006, 84.017006, 84.017006, 64.      , 64.      , 94.      ],
      dtype=float32)

In [22]:
ts.dimensions

array([84.017006, 84.017006, 84.017006, 64.      , 64.      , 94.      ],
      dtype=float32)

In [23]:
from MDAnalysis.coordinates.base import Timestep

In [24]:
%%time
t = Timestep(10)
t

CPU times: user 30 µs, sys: 11 µs, total: 41 µs
Wall time: 44.3 µs


< Timestep -1 with unit cell dimensions None >

In [25]:
%%timeit 
tstep = mdacore.TimestepContainer(10,dtype=np.float64)
tstep

296 ns ± 1.46 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [26]:
tstep.positions

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]])

In [27]:
tstep.dimensions

array([0., 1., 2., 3., 4., 5.])